### ISSUE TITLE
Modify Grammar and RCG pre-build scripts

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/Workbench#123]
We have determined the time it takes to use Maven to test for the existence of a jar file is longer than simply doing the build of them.  So both pre-build scripts should 
1. remove the maven test for jar
2. start with test for repo existence
a. if it exists, pull the latest main branch
b. if it does not, create the directory and pull
3. do the build.

@hammyau I just realized with the above procedures, if I hard-code a pull of main, one can't do development on the workbench using other branches for grammar and RC-apps.  What if we just did a "pull" without switching branches?  Then one can make RC and grammar have the right branches? (but having local changes would be problem...that won't work)

Do we just use the automated script to pull main then?

**Comment by hammyau** [comment]
Add a command line parameter to define the branch name.

**Comment by KipTwitchell** [comment]
OK, so additional thinking in this space, based upon our discussion:
- Build.sh will be maintained as a simple build script to build all the components across all repos (grammar, RC-apps)
   - It will be modified to accept (but not require) a branch name, which will be used across all repos (default will be main)

 - A new buildwb.sh will be placed inside the "Prebuild" directory, which can be used to build just the workbench
    - This script and grammar.sh and rcg.sh (renamed rc-apps.sh) will all accept (but not require) a branch name
    - default branch name will be main
    - They will test for an environment variable to be used for the source repo url
    - They will test for the existence of the local repo directory, creating it if it does not exist
    - If it exists, they will simply switch to the given branch
    - Pull to get the most current remote branch
    - They will build the components
 
This will mean that these scripts are not useful for local develop as the local repo status would be overwritten by the pull.
But they can be used to create any components needed for development which are not updated from remote.

**Comment by KipTwitchell** [comment]
Determined to externalize all git branches from the GitHub build scripts.  If branches exist, the build scripts will not not update them.  If they do not exists, they will be cloned, and the default (i.e., main) branch will be used in the build.

Although the Grammar Script could be consolidated under the RC-app repo (and then the resulting components are in place for the Workbench build which follows), The DB2 Jar imports are done differently for the RC Apps and for the workbench, so those remain separate.

**Comment by KipTwitchell** [comment]
Close with #126
